section .text:
    LD IMMEDIATE MESSAGE
    ST IMMEDIATE ITERATOR
    LD INDIRECT ITERATOR
    .lOOP
    ST IMMEDIATE #STDOUT
    LD DIRECT ITERATOR
    INC
    ST IMMEDIATE ITERATOR
    LD INDIRECT ITERATOR
    JNZ DIRECT .lOOP
    HLT
section .data:
    MESSAGE:"Hello World"
    ITERATOR:0
    ZERO:0